name: day09
channels:
  - conda-forge
  - defaults
dependencies:
  - imbalanced-learn
  - pandas
  - numpy
  - scikit-learn
  - seaborn
  - matplotlib
  - jupyter
  - notebook
  - scipy
  - scikit-image
  - keras